import { IncidentReport, ShiftSummary, Resident } from '../types';

// Plain-text renderers shared by every "Print / Download" action (staff
// IncidentsView and ShiftSummaryView, and the Caseworker portal) so the
// exported copy looks the same no matter who produced it.

export function buildIncidentDocumentText(incident: IncidentReport, residentName: string): string {
  return [
    'CAREHOMEOS — APPROVED INCIDENT REPORT',
    '='.repeat(40),
    `Resident: ${residentName}`,
    `Incident Type: ${incident.incident_type}`,
    `Severity: ${incident.severity}`,
    `Occurred At: ${incident.occurred_at}`,
    `Reported By: ${incident.reported_by_name}`,
    `Reported At: ${incident.reported_at}`,
    `Reviewed By: ${incident.reviewed_by_name || 'N/A'}`,
    `Reviewed At: ${incident.reviewed_at || 'N/A'}`,
    '',
    'Description:',
    incident.description,
    '',
    'Structured Details:',
    JSON.stringify(incident.type_details, null, 2),
  ].join('\n');
}

export function buildShiftSummaryDocumentText(summary: ShiftSummary): string {
  const lines = [
    'CAREHOMEOS — SHIFT SUMMARY',
    '='.repeat(40),
    `Date: ${summary.date}`,
    `Shift: ${summary.shift_type}`,
    `Generated By: ${summary.generated_by_name}`,
    `Generated At: ${summary.generated_at}`,
    '',
  ];
  for (const r of summary.residents) {
    lines.push(`— ${r.resident_name} (${r.daily_report_status}) —`);
    lines.push(`  Meals: ${r.meals_summary}`);
    lines.push(`  Shower Taken: ${r.shower_taken === null ? 'N/A' : r.shower_taken ? 'Yes' : 'No'}`);
    if (r.cigarette_count !== null) lines.push(`  Cigarettes: ${r.cigarette_count}`);
    lines.push(`  Observations: ${r.general_observations || 'None recorded.'}`);
    if (r.incident_ids.length > 0) lines.push(`  Related Incidents: ${r.incident_ids.length}`);
    lines.push('');
  }
  return lines.join('\n');
}
