import {
  Organization,
  Home,
  JurisdictionRuleset,
  Staff,
  Shift,
  ShiftAssignment,
  Prospect,
  Resident,
  CarePlan,
  Reassessment,
  MedicationOrder,
  MedicationAdministration,
  DailyReport,
  ShiftChecklist,
  IncidentReport,
  AuditEvent,
  NotificationItem,
  TaskDefinition,
  ShiftTaskTemplate,
} from './types';

// Seed shift-assignment dates are computed relative to "today" (rather than
// a fixed string) so the demo's shared shift-task board always has a
// current shift to generate tasks against, regardless of what day this is
// actually run on.
const TODAY = new Date().toISOString().split('T')[0];

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org-hihaven',
  name: 'Hi Haven Manor Inc.',
};

export const INITIAL_HOME: Home = {
  id: 'home-nl-01',
  organization_id: 'org-hihaven',
  name: 'Hi Haven Manor',
  address: '144 Topsail Road, St. John’s, NL A1E 2B1',
  capacity: 18,
  jurisdiction_code: 'CA-NL',
};

export const INITIAL_RULESET: JurisdictionRuleset = {
  id: 'ruleset-ca-nl-2022',
  code: 'CA-NL',
  jurisdiction_code: 'CA-NL',
  name: 'Newfoundland & Labrador Personal Care Home Operational Standards (2007, Rev 2022 Draft)',
  version: 2,
  effective_from: '2022-04-01',
  effective_to: null,
  required_staff_credential_types: [
    'Immunization Record',
    'Certificate of Conduct (Police / RNC)',
    'Vulnerable Sector Check',
    'Standard First Aid & CPR Level C',
  ],
  incident_record_immutability_required: true,
  compliance_review_frequency_days: 365,
  reassessment_frequency_days: 180,
  med_cart_lock_attestation_required: true,
  notes: 'NL Auditor General audit findings: Unlocked med storage carts & overdue resident reassessments are strictly monitored compliance exceptions.',
  rules: {
    reassessment_cycle_months: 6,
    fire_drill_frequency_days: 30,
    staff_ratio_day: '1:15',
    staff_ratio_night: '1:25',
    first_aid_recert_years: 3,
    police_check_renewal_years: 3,
    incident_report_retention_years: 7,
  },
};

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'staff-olatundun',
    home_id: 'home-nl-01',
    name: 'Olatundun Ndudim',
    role: 'Manager',
    username: 'olatundun.ndudim',
    email: 'o.ndudim@hihavenmanor.ca',
    phone: '(709) 555-0192',
    mfa_enabled: true,
    schedule_type: 'fixed_office',
    credentials: [
      { id: 'c-1', type: 'Standard First Aid & CPR Level C', title: 'Standard First Aid & CPR Level C', certificate_number: 'SFA-NL-8849', status: 'valid', expires_at: '2027-03-15', document_ref: 'DOC-FA-091' },
      { id: 'c-2', type: 'Certificate of Conduct (Police / RNC)', title: 'Certificate of Conduct (Police / RNC)', certificate_number: 'RNC-CC-2023-441', status: 'valid', expires_at: '2026-11-20', document_ref: 'DOC-RNC-441' },
      { id: 'c-3', type: 'Vulnerable Sector Check', title: 'Vulnerable Sector Check', certificate_number: 'VSC-NL-9901', status: 'valid', expires_at: '2026-11-20', document_ref: 'DOC-VSC-102' },
      { id: 'c-4', type: 'Immunization Record', title: 'Immunization Record (Mantoux / HepB)', certificate_number: 'IMM-NL-3320', status: 'valid', expires_at: '2028-01-01', document_ref: 'DOC-IMM-882' },
    ],
  },
  {
    id: 'staff-derrick',
    home_id: 'home-nl-01',
    name: 'Derrick Pike',
    role: 'Owner',
    username: 'derrick.pike',
    email: 'derrick@hihavenmanor.ca',
    phone: '(709) 555-0100',
    mfa_enabled: true,
    schedule_type: 'fixed_office',
    credentials: [
      { id: 'c-5', type: 'Standard First Aid & CPR Level C', title: 'Standard First Aid & CPR Level C', certificate_number: 'SFA-NL-7711', status: 'valid', expires_at: '2027-05-10', document_ref: 'DOC-FA-001' },
      { id: 'c-6', type: 'Certificate of Conduct (Police / RNC)', title: 'Certificate of Conduct (Police / RNC)', certificate_number: 'RNC-CC-2023-001', status: 'valid', expires_at: '2027-01-15', document_ref: 'DOC-RNC-001' },
    ],
  },
  {
    id: 'staff-sarah',
    home_id: 'home-nl-01',
    name: 'Sarah Jenkins',
    role: 'Care Worker',
    username: 'sarah.jenkins',
    email: 'sarah.j@hihavenmanor.ca',
    phone: '(709) 555-0211',
    mfa_enabled: true,
    schedule_type: 'rotating_shifts',
    credentials: [
      { id: 'c-7', type: 'Standard First Aid & CPR Level C', title: 'Standard First Aid & CPR Level C', certificate_number: 'SFA-NL-4921', status: 'valid', expires_at: '2026-10-30', document_ref: 'DOC-FA-332' },
      { id: 'c-8', type: 'Certificate of Conduct (Police / RNC)', title: 'Certificate of Conduct (Police / RNC)', certificate_number: 'RNC-CC-2023-201', status: 'valid', expires_at: '2026-12-01', document_ref: 'DOC-RNC-201' },
      { id: 'c-9', type: 'Vulnerable Sector Check', title: 'Vulnerable Sector Check', certificate_number: 'VSC-NL-4421', status: 'valid', expires_at: '2026-12-01', document_ref: 'DOC-VSC-399' },
      { id: 'c-10', type: 'Immunization Record', title: 'Immunization Record (Mantoux / HepB)', certificate_number: 'IMM-NL-8491', status: 'valid', expires_at: '2027-08-14', document_ref: 'DOC-IMM-319' },
    ],
  },
  {
    id: 'staff-dave',
    home_id: 'home-nl-01',
    name: 'Dave Tremblett',
    role: 'Care Worker',
    username: 'dave.tremblett',
    email: 'd.tremblett@hihavenmanor.ca',
    phone: '(709) 555-0344',
    mfa_enabled: true,
    schedule_type: 'rotating_shifts',
    credentials: [
      { id: 'c-11', type: 'Standard First Aid & CPR Level C', title: 'Standard First Aid & CPR Level C', certificate_number: 'SFA-NL-3301', status: 'expiring_soon', expires_at: '2026-09-21', document_ref: 'DOC-FA-110' },
      { id: 'c-12', type: 'Certificate of Conduct (Police / RNC)', title: 'Certificate of Conduct (Police / RNC)', certificate_number: 'RNC-CC-2023-550', status: 'valid', expires_at: '2027-04-12', document_ref: 'DOC-RNC-550' },
      { id: 'c-13', type: 'Vulnerable Sector Check', title: 'Vulnerable Sector Check', certificate_number: 'VSC-NL-8821', status: 'valid', expires_at: '2027-04-12', document_ref: 'DOC-VSC-550' },
      { id: 'c-14', type: 'Immunization Record', title: 'Immunization Record (Mantoux / HepB)', certificate_number: 'IMM-NL-2201', status: 'valid', expires_at: '2028-09-01', document_ref: 'DOC-IMM-120' },
    ],
  },
  {
    id: 'staff-mary',
    home_id: 'home-nl-01',
    name: 'Mary Power',
    role: 'Care Worker',
    username: 'mary.power',
    email: 'm.power@hihavenmanor.ca',
    phone: '(709) 555-0782',
    mfa_enabled: true,
    schedule_type: 'rotating_shifts',
    credentials: [
      { id: 'c-15', type: 'Standard First Aid & CPR Level C', title: 'Standard First Aid & CPR Level C', certificate_number: 'SFA-NL-9011', status: 'valid', expires_at: '2027-02-14', document_ref: 'DOC-FA-412' },
      { id: 'c-16', type: 'Certificate of Conduct (Police / RNC)', title: 'Certificate of Conduct (Police / RNC)', certificate_number: 'RNC-CC-2023-612', status: 'valid', expires_at: '2026-11-19', document_ref: 'DOC-RNC-612' },
      { id: 'c-17', type: 'Vulnerable Sector Check', title: 'Vulnerable Sector Check', certificate_number: 'VSC-NL-1149', status: 'valid', expires_at: '2026-11-19', document_ref: 'DOC-VSC-612' },
      { id: 'c-18', type: 'Immunization Record', title: 'Immunization Record (Mantoux / HepB)', certificate_number: 'IMM-NL-7721', status: 'valid', expires_at: '2027-04-10', document_ref: 'DOC-IMM-901' },
    ],
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift-day-today',
    home_id: 'home-nl-01',
    shift_type: 'Day Shift (07:00 - 19:00)',
    starts_at: '07:00',
    ends_at: '19:00',
    required_staff_count: 2,
  },
  {
    id: 'shift-night-today',
    home_id: 'home-nl-01',
    shift_type: 'Night Shift (19:00 - 07:00)',
    starts_at: '19:00',
    ends_at: '07:00',
    required_staff_count: 1,
  },
  {
    id: 'shift-mgr-office',
    home_id: 'home-nl-01',
    shift_type: 'Manager Schedule (Mon-Fri 09:00 - 15:00)',
    starts_at: '09:00',
    ends_at: '15:00',
    required_staff_count: 1,
  },
];

export const INITIAL_SHIFT_ASSIGNMENTS: ShiftAssignment[] = [
  {
    id: 'assign-sarah-day',
    staff_id: 'staff-sarah',
    shift_id: 'shift-day-today',
    date: TODAY,
    clocked_in_at: `${TODAY}T06:55:00Z`,
    clocked_out_at: null,
    is_active: true,
  },
  {
    id: 'assign-mary-day',
    staff_id: 'staff-mary',
    shift_id: 'shift-day-today',
    date: TODAY,
    clocked_in_at: `${TODAY}T07:02:00Z`,
    clocked_out_at: null,
    is_active: true,
  },
  {
    id: 'assign-olatundun-mgr',
    staff_id: 'staff-olatundun',
    shift_id: 'shift-mgr-office',
    date: TODAY,
    clocked_in_at: `${TODAY}T08:58:00Z`,
    clocked_out_at: null,
    is_active: true,
  },
];

// ==========================================
// SHARED SHIFT TASKS — task catalog + which tasks occur on which shift type.
// Owner-adjustable via the Owner Dashboard's Shift Task Setup panel.
// ==========================================

export const INITIAL_TASK_DEFINITIONS: TaskDefinition[] = [
  { id: 'task-shower', home_id: 'home-nl-01', name: 'Assist with Shower / Personal Hygiene', category: 'resident_care', applies_to: 'resident', frequency: 'once', is_active: true },
  { id: 'task-med-pass', home_id: 'home-nl-01', name: 'Medication Pass', category: 'medication', applies_to: 'resident', frequency: 'once', is_active: true },
  { id: 'task-breakfast', home_id: 'home-nl-01', name: 'Prepare & Serve Breakfast', category: 'meal', applies_to: 'home', frequency: 'once', is_active: true },
  { id: 'task-lunch', home_id: 'home-nl-01', name: 'Prepare & Serve Lunch', category: 'meal', applies_to: 'home', frequency: 'once', is_active: true },
  { id: 'task-dinner', home_id: 'home-nl-01', name: 'Prepare & Serve Dinner', category: 'meal', applies_to: 'home', frequency: 'once', is_active: true },
  { id: 'task-housekeeping', home_id: 'home-nl-01', name: 'General Housekeeping', category: 'cleaning', applies_to: 'home', frequency: 'once', is_active: true },
  { id: 'task-night-med-pass', home_id: 'home-nl-01', name: 'Night Medication Pass', category: 'medication', applies_to: 'resident', frequency: 'once', is_active: true },
  { id: 'task-night-cleaning', home_id: 'home-nl-01', name: 'General Cleaning', category: 'cleaning', applies_to: 'home', frequency: 'once', is_active: true },
  { id: 'task-hourly-walkthrough', home_id: 'home-nl-01', name: 'Hourly Safety Walkthrough', category: 'safety_check', applies_to: 'home', frequency: 'hourly', is_active: true },
];

export const INITIAL_SHIFT_TASK_TEMPLATES: ShiftTaskTemplate[] = [
  { id: 'stt-day-shower', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-shower', is_active: true },
  { id: 'stt-day-meds', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-med-pass', is_active: true },
  { id: 'stt-day-breakfast', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-breakfast', is_active: true },
  { id: 'stt-day-lunch', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-lunch', is_active: true },
  { id: 'stt-day-dinner', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-dinner', is_active: true },
  { id: 'stt-day-housekeeping', home_id: 'home-nl-01', shift_type: 'Day Shift (07:00 - 19:00)', task_definition_id: 'task-housekeeping', is_active: true },
  { id: 'stt-night-meds', home_id: 'home-nl-01', shift_type: 'Night Shift (19:00 - 07:00)', task_definition_id: 'task-night-med-pass', is_active: true },
  { id: 'stt-night-cleaning', home_id: 'home-nl-01', shift_type: 'Night Shift (19:00 - 07:00)', task_definition_id: 'task-night-cleaning', is_active: true },
  { id: 'stt-night-walkthrough', home_id: 'home-nl-01', shift_type: 'Night Shift (19:00 - 07:00)', task_definition_id: 'task-hourly-walkthrough', is_active: true },
];

export const INITIAL_PROSPECTS: Prospect[] = [
  {
    id: 'prospect-01',
    home_id: 'home-nl-01',
    full_name: 'Gordon Fardy',
    age: 78,
    referral_source: 'Eastern Health Central Intake',
    care_needs: 'Level 2 Personal Care, insulin support, mild cognitive impairment',
    funding_status: 'Subsidized - Eastern Health',
    pipeline_stage: 'Tour',
    contact_phone: '(709) 722-4491',
    notes: 'Family attended tour on Thursday. Son Sean is primary contact. Assessment approved by Eastern Health social worker.',
    created_at: '2026-08-25T14:30:00Z',
  },
  {
    id: 'prospect-02',
    home_id: 'home-nl-01',
    full_name: 'Evelyn Murphy',
    age: 82,
    referral_source: 'St. Clare’s Mercy Hospital Discharge Planning',
    care_needs: 'Post-hip fracture rehab convalescence, assistance with bathing, medication prompts',
    funding_status: 'Private Pay',
    pipeline_stage: 'Accepted',
    contact_phone: '(709) 685-1190',
    notes: 'Bed reserved in Room 14 for next Monday move-in. Ready for conversion to resident upon arrival.',
    created_at: '2026-08-28T09:15:00Z',
  },
  {
    id: 'prospect-03',
    home_id: 'home-nl-01',
    full_name: 'Patrick Roche',
    age: 71,
    referral_source: 'Community Physician Referral (Dr. Mercer)',
    care_needs: 'Level 1 supervision, early Alzheimer’s, wander-guard consideration',
    funding_status: 'Pending Assessment',
    pipeline_stage: 'Assessment',
    contact_phone: '(709) 579-2238',
    notes: 'Awaiting financial means assessment review from Dept of Children, Seniors & Social Development.',
    created_at: '2026-09-02T11:00:00Z',
  },
];

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: 'res-arthur-walsh',
    home_id: 'home-nl-01',
    prospect_id: 'prospect-legacy-01',
    full_name: 'Arthur Walsh',
    room_number: '101',
    dob: '1944-03-12',
    age: 82,
    status: 'active',
    admission_date: '2024-02-15',
    level_of_care: 'Level 2',
    funding_status: 'Subsidized - Eastern Health',
    emergency_contact: { name: 'Brenda Walsh (Daughter)', relationship: 'Daughter', phone: '(709) 745-8890' },
    on_cigarette_program: true,
    primary_physician: 'Dr. Katherine Mercer',
    allergies: ['Penicillin', 'Sulfa drugs'],
  },
  {
    id: 'res-florence-reid',
    home_id: 'home-nl-01',
    full_name: 'Florence Reid',
    room_number: '104',
    dob: '1939-11-04',
    age: 86,
    status: 'active',
    admission_date: '2023-08-10',
    level_of_care: 'Level 2',
    funding_status: 'Subsidized - Eastern Health',
    emergency_contact: { name: 'David Reid (Son)', relationship: 'Son', phone: '(709) 682-3401' },
    on_cigarette_program: false,
    primary_physician: 'Dr. Michael Collins',
    allergies: ['Codeine'],
  },
  {
    id: 'res-harold-drover',
    home_id: 'home-nl-01',
    full_name: 'Harold Drover',
    room_number: '107',
    dob: '1951-06-22',
    age: 75,
    status: 'active',
    admission_date: '2024-11-01',
    level_of_care: 'Level 1',
    funding_status: 'Private Pay',
    emergency_contact: { name: 'Gail Drover (Sister)', relationship: 'Sister', phone: '(709) 726-1188' },
    on_cigarette_program: true,
    primary_physician: 'Dr. Katherine Mercer',
    allergies: ['Latex'],
  },
  {
    id: 'res-beatrice-noel',
    home_id: 'home-nl-01',
    full_name: 'Beatrice Noel',
    room_number: '110',
    dob: '1947-01-30',
    age: 79,
    status: 'active',
    admission_date: '2025-01-14',
    level_of_care: 'Level 2',
    funding_status: 'Subsidized - Eastern Health',
    emergency_contact: { name: 'Karen Noel (Niece)', relationship: 'Niece', phone: '(709) 693-5512' },
    on_cigarette_program: false,
    primary_physician: 'Dr. Susan Bartlett',
    allergies: ['Shellfish'],
  },
  {
    id: 'res-kenneth-power',
    home_id: 'home-nl-01',
    full_name: 'Kenneth Power',
    room_number: '112',
    dob: '1948-09-18',
    age: 77,
    status: 'active',
    admission_date: '2025-04-03',
    level_of_care: 'Level 2',
    funding_status: 'Subsidized - Eastern Health',
    emergency_contact: { name: 'Liam Power (Brother)', relationship: 'Brother', phone: '(709) 749-0023' },
    on_cigarette_program: true,
    primary_physician: 'Dr. Michael Collins',
    allergies: [],
  },
];

export const INITIAL_CARE_PLANS: CarePlan[] = [
  {
    id: 'cp-arthur-v2',
    resident_id: 'res-arthur-walsh',
    version: 2,
    status: 'active',
    created_at: '2026-03-01T10:00:00Z',
    signed_by_manager: 'Olatundun Ndudim',
    signed_at: '2026-03-01T14:30:00Z',
    dietary_needs: 'Diabetic texture-modified diet (low sodium, consistent carbohydrate). Needs cueing for hydration.',
    mobility_needs: 'Two-wheeled walker. One-person standby assist for morning transfers.',
    behavioral_triggers: 'Sundowning agitation around 16:30. Benefits from quiet tea break and classical music.',
    adl_goals: ['Maintain independent ambulation with walker', 'Participate in morning exercise group 3x/week'],
    supervision_level: 'Close observation during meals and ambulation',
  },
  {
    id: 'cp-florence-v1',
    resident_id: 'res-florence-reid',
    version: 1,
    status: 'active',
    created_at: '2025-10-15T11:00:00Z',
    signed_by_manager: 'Olatundun Ndudim',
    signed_at: '2025-10-16T09:00:00Z',
    dietary_needs: 'Regular diet, minced meats. Prefers tea with evaporated milk.',
    mobility_needs: 'Rollator walker. Standby assist for shower stall entry.',
    behavioral_triggers: 'Dislikes rushed care routines. Allow extra time in mornings.',
    adl_goals: ['Complete upper-body dressing independently', 'Shower 2x/week on Tuesday/Friday'],
    supervision_level: 'Routine care-worker checks q2h',
  },
];

export const INITIAL_REASSESSMENTS: Reassessment[] = [
  {
    id: 'reassess-arthur-2026',
    resident_id: 'res-arthur-walsh',
    due_date: '2026-08-30', // Overdue! NL Auditor General finding flag
    completed_date: null,
    completed_by: null,
    status: 'overdue',
    outcome_notes: 'Due for 6-month clinical review. Mobility decline noted by day staff.',
    resulting_care_plan_id: null,
  },
  {
    id: 'reassess-florence-2026',
    resident_id: 'res-florence-reid',
    due_date: '2026-09-15',
    completed_date: null,
    completed_by: null,
    status: 'scheduled',
    outcome_notes: 'Upcoming annual AHCD comprehensive assessment with community coordinator.',
    resulting_care_plan_id: null,
  },
  {
    id: 'reassess-harold-2026',
    resident_id: 'res-harold-drover',
    due_date: '2026-05-01',
    completed_date: '2026-04-28',
    completed_by: 'Olatundun Ndudim',
    status: 'completed',
    outcome_notes: 'Cognitive stability confirmed. Continues on cigarette program (4 allotted times daily).',
    resulting_care_plan_id: 'cp-harold-v1',
  },
];

export const INITIAL_MED_ORDERS: MedicationOrder[] = [
  {
    id: 'med-ord-01',
    resident_id: 'res-arthur-walsh',
    drug_name: 'Metformin HCl',
    dose: '500 mg',
    route: 'Oral',
    schedule_times: ['08:00', '18:00'],
    prescriber: 'Dr. Katherine Mercer',
    is_prn: false,
    indication: 'Type 2 Diabetes Mellitus',
  },
  {
    id: 'med-ord-02',
    resident_id: 'res-arthur-walsh',
    drug_name: 'Ramipril',
    dose: '5 mg',
    route: 'Oral',
    schedule_times: ['08:00'],
    prescriber: 'Dr. Katherine Mercer',
    is_prn: false,
    indication: 'Hypertension',
  },
  {
    id: 'med-ord-03',
    resident_id: 'res-arthur-walsh',
    drug_name: 'Lorazepam',
    dose: '0.5 mg',
    route: 'Sublingual',
    schedule_times: ['PRN'],
    prescriber: 'Dr. Katherine Mercer',
    is_prn: true,
    indication: 'Acute severe sundowning anxiety (max 1x per 24h)',
  },
  {
    id: 'med-ord-04',
    resident_id: 'res-florence-reid',
    drug_name: 'Amlodipine',
    dose: '5 mg',
    route: 'Oral',
    schedule_times: ['08:00'],
    prescriber: 'Dr. Michael Collins',
    is_prn: false,
    indication: 'Hypertension',
  },
  {
    id: 'med-ord-05',
    resident_id: 'res-harold-drover',
    drug_name: 'Donepezil',
    dose: '10 mg',
    route: 'Oral',
    schedule_times: ['20:00'],
    prescriber: 'Dr. Katherine Mercer',
    is_prn: false,
    indication: 'Mild Cognitive Impairment',
  },
];

export const INITIAL_MED_ADMINS: MedicationAdministration[] = [
  {
    id: 'med-adm-01',
    order_id: 'med-ord-01',
    resident_id: 'res-arthur-walsh',
    shift_id: 'shift-day-today',
    administered_by: 'staff-sarah',
    administered_by_name: 'Sarah Jenkins',
    timestamp: '2026-09-07T08:12:00Z',
    scheduled_time: '08:00',
    dose_given: '500 mg',
    status: 'given',
    notes: 'Taken with breakfast oatmeal without difficulty.',
    is_correction: false,
  },
  {
    id: 'med-adm-02',
    order_id: 'med-ord-02',
    resident_id: 'res-arthur-walsh',
    shift_id: 'shift-day-today',
    administered_by: 'staff-sarah',
    administered_by_name: 'Sarah Jenkins',
    timestamp: '2026-09-07T08:12:00Z',
    scheduled_time: '08:00',
    dose_given: '5 mg',
    status: 'given',
    notes: 'BP prior 132/78 mmHg.',
    is_correction: false,
  },
  {
    id: 'med-adm-03',
    order_id: 'med-ord-04',
    resident_id: 'res-florence-reid',
    shift_id: 'shift-day-today',
    administered_by: 'staff-sarah',
    administered_by_name: 'Sarah Jenkins',
    timestamp: '2026-09-07T08:25:00Z',
    scheduled_time: '08:00',
    dose_given: '5 mg',
    status: 'given',
    notes: 'Resident in dining room.',
    is_correction: false,
  },
];

export const INITIAL_DAILY_REPORTS: DailyReport[] = [
  {
    id: 'report-arthur-today',
    resident_id: 'res-arthur-walsh',
    shift_id: 'shift-day-today',
    date: '2026-09-07',
    authored_by: 'staff-sarah',
    authored_by_name: 'Sarah Jenkins',
    meals: {
      breakfast: { offered: true, eaten: 'all', notes: 'Poached egg, oatmeal, cranberry juice' },
      lunch: { offered: true, eaten: 'half', notes: 'Turkey sandwich, soup; left crusts' },
      dinner: { offered: false, eaten: 'refused', notes: 'Pending dinner pass' },
    },
    shower_taken: true,
    shower_notes: 'Full shower assisted. Skin warm and dry. Small 2cm superficial red mark on left heel observed, barrier cream applied.',
    cigarette_program_given: true,
    cigarette_count: 2,
    cigarette_times: ['10:00', '14:00'],
    general_observations: 'Good spirits this morning. Participated in afternoon musical bingo. Slight restlessness noticed around 15:30.',
    status: 'draft',
  },
  {
    id: 'report-florence-today',
    resident_id: 'res-florence-reid',
    shift_id: 'shift-day-today',
    date: '2026-09-07',
    authored_by: 'staff-sarah',
    authored_by_name: 'Sarah Jenkins',
    meals: {
      breakfast: { offered: true, eaten: 'all', notes: 'Toast and poached egg' },
      lunch: { offered: true, eaten: 'all', notes: 'Fish cakes and chowder' },
      dinner: { offered: false, eaten: 'refused', notes: 'Pending dinner pass' },
    },
    shower_taken: false,
    shower_notes: 'Scheduled for Tuesday/Friday showers.',
    cigarette_program_given: null,
    cigarette_count: 0,
    cigarette_times: [],
    general_observations: 'Enjoyed telephone call with daughter Brenda. Rested quietly in armchair after lunch.',
    status: 'draft',
  },
];

export const INITIAL_SHIFT_CHECKLISTS: ShiftChecklist[] = [
  {
    id: 'checklist-night-prev',
    shift_id: 'shift-night-prev',
    date: '2026-09-06',
    completed_by: 'staff-dave',
    completed_by_name: 'Dave Tremblett',
    medication_storage_secured: true,
    medication_count_verified: true,
    fridge_temp_celsius: 3.4,
    safety_rounds_completed: true,
    notes: 'All residents settled quietly. Double-lock verified on narcotics cabinet at 06:45.',
    completed_at: '2026-09-07T06:50:00Z',
  },
];

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-2026-001',
    resident_id: 'res-arthur-walsh',
    home_id: 'home-nl-01',
    reported_by: 'staff-sarah',
    reported_by_name: 'Sarah Jenkins',
    occurred_at: '2026-09-06T17:45:00Z',
    reported_at: '2026-09-06T18:10:00Z',
    incident_type: 'fall_injury',
    severity: 'Medium',
    description: 'Resident lost footing while transferring from dining room chair to walker. Lowered gently to carpeted floor by staff.',
    type_details: {
      location: 'Dining Room south corner',
      witnessed: true,
      first_aid_given: true,
      injury_description: 'Minor superficial abrasion on left forearm. Ice pack applied. ROM intact, no hip tenderness.',
      vital_signs: 'BP 128/76, HR 74 regular',
    },
    status: 'submitted',
    reviewed_by: null,
    reviewed_by_name: null,
    reviewed_at: null,
    rejection_reason: null,
  },
  {
    id: 'inc-2026-002',
    resident_id: 'res-harold-drover',
    home_id: 'home-nl-01',
    reported_by: 'staff-mary',
    reported_by_name: 'Mary Power',
    occurred_at: '2026-09-05T14:20:00Z',
    reported_at: '2026-09-05T14:50:00Z',
    incident_type: 'behavioral',
    severity: 'Medium',
    description: 'Verbal aggression during afternoon smoking schedule transition. Resident demanded additional cigarette outside scheduled allotment.',
    type_details: {
      target: 'Staff (Mary Power)',
      subtype: 'Verbal',
      de_escalation_used: 'Offered herbal tea in gazebo, redirected to music playlist. Calm within 10 minutes.',
      injuries: false,
    },
    status: 'approved',
    reviewed_by: 'staff-olatundun',
    reviewed_by_name: 'Olatundun Ndudim',
    reviewed_at: '2026-09-05T16:00:00Z',
    rejection_reason: null,
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'evt-1001',
    actor_id: 'staff-sarah',
    actor_name: 'Sarah Jenkins',
    action: 'MEDICATION_ADMINISTERED',
    resource_type: 'medication_administrations',
    resource_id: 'med-adm-01',
    payload: { drug: 'Metformin HCl 500mg', resident: 'Arthur Walsh', dose: '500 mg', route: 'Oral' },
    prior_event_id: null,
    created_at: '2026-09-07T08:12:00Z',
  },
  {
    id: 'evt-1002',
    actor_id: 'staff-sarah',
    actor_name: 'Sarah Jenkins',
    action: 'MEDICATION_ADMINISTERED',
    resource_type: 'medication_administrations',
    resource_id: 'med-adm-02',
    payload: { drug: 'Ramipril 5mg', resident: 'Arthur Walsh', dose: '5 mg', route: 'Oral' },
    prior_event_id: null,
    created_at: '2026-09-07T08:12:00Z',
  },
  {
    id: 'evt-1003',
    actor_id: 'staff-sarah',
    actor_name: 'Sarah Jenkins',
    action: 'INCIDENT_SUBMITTED',
    resource_type: 'incident_reports',
    resource_id: 'inc-2026-001',
    payload: { incident_type: 'fall_injury', severity: 'Medium', resident: 'Arthur Walsh' },
    prior_event_id: null,
    created_at: '2026-09-06T18:10:00Z',
  },
  {
    id: 'evt-1004',
    actor_id: 'staff-dave',
    actor_name: 'Dave Tremblett',
    action: 'SHIFT_CHECKLIST_COMPLETED',
    resource_type: 'shift_checklists',
    resource_id: 'checklist-night-prev',
    payload: { medication_storage_secured: true, medication_count_verified: true, fridge_temp: 3.4 },
    prior_event_id: null,
    created_at: '2026-09-07T06:50:00Z',
  },
  {
    id: 'evt-1005',
    actor_id: 'staff-olatundun',
    actor_name: 'Olatundun Ndudim',
    action: 'INCIDENT_APPROVED',
    resource_type: 'incident_reports',
    resource_id: 'inc-2026-002',
    payload: { reviewer: 'Olatundun Ndudim', approved_status: 'approved' },
    prior_event_id: null,
    created_at: '2026-09-05T16:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    recipient_role: 'Manager',
    recipient_name: 'Olatundun Ndudim',
    channel: 'push',
    title: '⚠️ Incident Report Submitted for Review',
    body: 'Sarah Jenkins submitted incident report (fall_injury - Medium severity) for Arthur Walsh. Waiting for manager review.',
    created_at: '2026-09-06T18:10:00Z',
    read: false,
    urgency: 'high',
  },
  {
    id: 'notif-02',
    recipient_role: 'Manager',
    recipient_name: 'Olatundun Ndudim',
    channel: 'in_app',
    title: '⏰ Credential Expiring: Dave Tremblett',
    body: 'Standard First Aid & CPR Level C expires in 14 days (2026-09-21). Action required to maintain CA-NL compliance.',
    created_at: '2026-09-07T07:00:00Z',
    read: false,
    urgency: 'high',
  },
  {
    id: 'notif-03',
    recipient_role: 'Manager',
    recipient_name: 'Olatundun Ndudim',
    channel: 'in_app',
    title: '📋 Overdue Resident Reassessment: Arthur Walsh',
    body: 'Reassessment due date was 2026-08-30. Flagged on CA-NL compliance monitor.',
    created_at: '2026-08-31T08:00:00Z',
    read: true,
    urgency: 'routine',
  },
];
